name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # Supported Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: pwsh  # Use PowerShell
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
              pip install -r requirements.txt
          }
          if (Test-Path pyproject.toml) {
              pip install poetry
              poetry install --no-root
          }

      - name: Run linters
        shell: pwsh
        run: |
          pip install flake8 black isort mypy
          flake8 .
          black --check .
          isort --check-only .
          mypy .

      - name: Run tests
        shell: pwsh
        run: |
          pip install pytest
          pytest --maxfail=10 --disable-warnings
