name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # Use supported Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (pip install -r requirements.txt)
          if exist pyproject.toml (pip install poetry && poetry install --no-root)

      - name: Run linters
        run: |
          pip install flake8 black isort mypy
          flake8 .
          black --check .
          isort --check-only .
          mypy .

      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=10 --disable-warnings
